# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MultiK8s < Formula
  desc "CLI to create k8s clusters on Multipass VMs."
  homepage "https://github.com/andrei-don/multi-k8s"
  version "0.0.4"

  on_macos do
    on_arm do
      url "https://github.com/andrei-don/multi-k8s/releases/download/v0.0.4/multi-k8s_0.0.4_darwin_arm64.tar.gz"
      sha256 "9aaafd5a0bc7f933b5c48e62764db1f9a1f90eefe1812d8c59d3d4b070016190"

      def install
        bin.install "multi-k8s"
      end
    end
  end

  on_linux do
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/andrei-don/multi-k8s/releases/download/v0.0.4/multi-k8s_0.0.4_linux_arm64.tar.gz"
        sha256 "708f3622f560ef48b4fea9165a8f195bbf28e7c2d58e632b5caaf112147cb76e"

        def install
          bin.install "multi-k8s"
        end
      end
    end
  end
end
