# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MultiK8s < Formula
  desc "CLI to create k8s clusters on Multipass VMs."
  homepage "https://github.com/andrei-don/multi-k8s"
  version "0.0.3"

  on_macos do
    on_arm do
      url "https://github.com/andrei-don/multi-k8s/releases/download/v0.0.3/multi-k8s_0.0.3_darwin_arm64.tar.gz"
      sha256 "396305b95c90165d943d4e8938d6970b51888104c2cfb092e019ec765471a02b"

      def install
        bin.install "multi-k8s"
      end
    end
  end

  on_linux do
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/andrei-don/multi-k8s/releases/download/v0.0.3/multi-k8s_0.0.3_linux_arm64.tar.gz"
        sha256 "bb03e1d754753db835bd23b60abba822faf0a0a7d4df37596517524216e9efbe"

        def install
          bin.install "multi-k8s"
        end
      end
    end
  end
end
